<?php

return [
    [
        'tab' => 1,
        'category' => 'spaletta',
        'name' => 29,
        'alt' => ''
    ],
    [
        'tab' => 1,
        'category' => 'spaletta',
        'name' => 30,
    ],
    [
        'tab' => 1,
        'category' => 'spaletta',
        'name' => 31,
    ],
    [
        'tab' => 1,
        'category' => 'spaletta',
        'name' => 32,
    ],
    [
        'tab' => 1,
        'category' => 'spaletta',
        'name' => 33,
    ],
    ["tab" => 3, "category" => "beer", "name" => "beer/S1"],
    ["tab" => 3, "category" => "beer", "name" => "beer/S2"],
    ["tab" => 3, "category" => "beer", "name" => "beer/S3"],
    ["tab" => 3, "category" => "beer", "name" => "beer/S4"],
    ["tab" => 3, "category" => "beer", "name" => "beer/S5"],
    ["tab" => 3, "category" => "beer", "name" => "beer/S6"],
    ["tab" => 3, "category" => "beer", "name" => "beer/S7"],
    [
        'tab' => 3,
        'category' => 'beer',
        'name' => 15,
    ],
    [
        'tab' => 3,
        'category' => 'beer',
        'name' => 16,
    ],
    [
        'tab' => 3,
        'category' => 'beer',
        'name' => 17,
    ],
    [
        'tab' => 3,
        'category' => 'beer',
        'name' => 18,
    ],
    [
        'tab' => 3,
        'category' => 'beer',
        'name' => 19,
    ],
    [
        'tab' => 3,
        'category' => 'beer',
        'name' => 20,
    ],
    [
        'tab' => 3,
        'category' => 'beer',
        'name' => 21,
    ],
    [
        'tab' => 3,
        'category' => 'beer',
        'name' => 22,
    ],
    [
        'tab' => 3,
        'category' => 'beer',
        'name' => 23,
    ],
    [
        'tab' => 3,
        'category' => 'beer',
        'name' => 24,
    ],
    [
        'tab' => 3,
        'category' => 'beer',
        'name' => 25,
    ],
    [
        'tab' => 3,
        'category' => 'beer',
        'name' => 26,
    ],
    [
        'tab' => 3,
        'category' => 'beer',
        'name' => 27,
    ],
    [
        'tab' => 3,
        'category' => 'beer',
        'name' => 28,
    ],
    ["tab" => 2, "category" => "restaurent", "name" => "restaurent/S23"],
    ["tab" => 2, "category" => "restaurent", "name" => "restaurent/S24"],
    ["tab" => 2, "category" => "restaurent", "name" => "restaurent/S25"],
    ["tab" => 2, "category" => "restaurent", "name" => "restaurent/S26"],
    ["tab" => 2, "category" => "restaurent", "name" => "restaurent/S27"],
    ["tab" => 2, "category" => "restaurent", "name" => "restaurent/S28"],
    ["tab" => 2, "category" => "restaurent", "name" => "restaurent/S29"],
    ["tab" => 2, "category" => "restaurent", "name" => "restaurent/S30"],
    ["tab" => 2, "category" => "restaurent", "name" => "restaurent/S31"],
    [
        'tab' => 2,
        'category' => 'restaurent',
        'name' => 1,
    ],
    [
        'tab' => 2,
        'category' => 'restaurent',
        'name' => 2,
    ],
    [
        'tab' => 2,
        'category' => 'restaurent',
        'name' => 3,
    ],
    [
        'tab' => 2,
        'category' => 'restaurent',
        'name' => 4,
    ],
    [
        'tab' => 2,
        'category' => 'restaurent',
        'name' => 5,
    ],
    [
        'tab' => 2,
        'category' => 'restaurent',
        'name' => 6,
    ],
    [
        'tab' => 2,
        'category' => 'restaurent',
        'name' => 7,
    ],
    [
        'tab' => 2,
        'category' => 'restaurent',
        'name' => 8,
    ],
    [
        'tab' => 2,
        'category' => 'restaurent',
        'name' => 9,
    ],
    [
        'tab' => 2,
        'category' => 'restaurent',
        'name' => 10,
    ],
    [
        'tab' => 2,
        'category' => 'restaurent',
        'name' => 11,
    ],
    [
        'tab' => 2,
        'category' => 'restaurent',
        'name' => 12,
    ],
    [
        'tab' => 2,
        'category' => 'restaurent',
        'name' => 13,
    ],
    [
        'tab' => 2,
        'category' => 'restaurent',
        'name' => 14,
    ],
    ["tab" => 5, "category" => "events", "name" => "events/S7"],
    ["tab" => 5, "category" => "events", "name" => "events/S8"],
    ["tab" => 5, "category" => "events", "name" => "events/S9"],
    ["tab" => 5, "category" => "events", "name" => "events/S10"],
    ["tab" => 5, "category" => "events", "name" => "events/S11"],
    ["tab" => 5, "category" => "events", "name" => "events/S12"],
    ["tab" => 5, "category" => "events", "name" => "events/S13"],
    ["tab" => 5, "category" => "events", "name" => "events/S14"],
    ["tab" => 5, "category" => "events", "name" => "events/S15"],
    ["tab" => 5, "category" => "events", "name" => "events/S16"],
    ["tab" => 5, "category" => "events", "name" => "events/S17"],
    ["tab" => 5, "category" => "events", "name" => "events/S18"],
    ["tab" => 5, "category" => "events", "name" => "events/S19"],
    ["tab" => 5, "category" => "events", "name" => "events/S20"],
    ["tab" => 5, "category" => "events", "name" => "events/S21"],
    ["tab" => 5, "category" => "events", "name" => "events/S22"],
    ["tab" => 5, "category" => "events", "name" => "events/S32"],
    ["tab" => 5, "category" => "events", "name" => "events/S33"],
    ["tab" => 5, "category" => "events", "name" => "events/S34"],
    ["tab" => 5, "category" => "events", "name" => "events/S35"],
    ["tab" => 5, "category" => "events", "name" => "events/S36"],
    [
        'tab' => 5,
        'category' => 'events',
        'name' => 36,
    ],
    [
        'tab' => 5,
        'category' => 'events',
        'name' => 38,
    ],
    [
        'tab' => 5,
        'category' => 'events',
        'name' => 39,
    ],
    [
        'tab' => 5,
        'category' => 'events',
        'name' => 40,
    ],
    [
        'tab' => 5,
        'category' => 'events',
        'name' => 41,
    ],
    [
        'tab' => 5,
        'category' => 'events',
        'name' => 42,
    ],
    [
        'tab' => 5,
        'category' => 'events',
        'name' => 43,
    ],
    [
        'tab' => 5,
        'category' => 'events',
        'name' => 44,
    ],
    [
        'tab' => 5,
        'category' => 'events',
        'name' => 45,
    ],
    [
        'tab' => 5,
        'category' => 'events',
        'name' => 46,
    ],
    [
        'tab' => 5,
        'category' => 'events',
        'name' => 47,
    ],
    [
        'tab' => 5,
        'category' => 'events',
        'name' => 48,
    ],
    [
        'tab' => 5,
        'category' => 'events',
        'name' => 49,
    ],
    [
        'tab' => 5,
        'category' => 'events',
        'name' => 50,
    ],
    [
        'tab' => 5,
        'category' => 'events',
        'name' => 51,
    ],
    // [
    //     'tab' => 4,
    //     'category' => 'team',
    //     'name' => 109,
    // ],
];
